class States:
	"""States: legal states in the state machine. The state values are
	strings so they can be displayed meaningfully (as opposed to numbers)
	and can be ordered by their values."""
	new='A_new'
	check_registered='B_check_registered'
	wait_for_data='C_wait_for_data'
	make_sample_sheet='D_make_sample_sheet'
	check_single_index_length='E_check_single_index_length'
	simple_bcl_convert='F_simple_bcl_convert'
	complex_bcl_convert='G_complex_bcl_convert'
	merge_bcl_conversions='H_merge_bcl_conversions'
	distribute_demultiplexed='J_distribute_demultiplexed'
	cleanup ='K_cleanup' 
	qc='L_qc'
	archive='M_archive'
	complete='N_complete'
	error_detected='O_error_detected'
	error_notified='P_error_notified'
	reprocess='Q_reprocess'
	check_if_miseq='R_check_if_miseq'
	check_if_patchpcr='S_check_if_patchpcr'
	patchpcr_sample_sheet='T_patchpcr_sample_sheet'
	patchpcr_demultiplex='U_patchpcr_demultiplex'
	patchpcr_postprocess='V_patchpcr_postprocess'
	patchpcr_distribute='W_patchpcr_distribute'
	check_if_kappapcr='X_check_if_kappapcr'
	kappapcr_sample_sheet='Y_kappapcr_sample_sheet'
	kappapcr_demultiplex='Z_kappapcr_demultiplex'
	kappapcr_postprocess='a_kappapcr_postprocess'
	kappapcr_distribute='b_kappapcr_distribute'
	Miseq_qc='c_miseq_qc'
