# custom_handling allows us to turn on and off pipeline features for
# special runs from AmpliconExpress. With this set to False, samples
# from Amplicon Express are handled like regular samples.
custom_handling=False
firstname = 'Travis'
lastname = 'Ruff'
fullname = 'Travis Ruff'
SampleSheet="""<fcid>,<lane>,L<lane>T01A01,None,GCAACCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B01,None,TGTGACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C01,None,GACTTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D01,None,CCTTAAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E01,None,GATGACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F01,None,TCGTCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G01,None,GATGAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H01,None,GAAGACCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A02,None,GGTAGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B02,None,CTACCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C02,None,CCAAGGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D02,None,GCTAATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E02,None,CTGAGACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F02,None,CCAACCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G02,None,GTTGACGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H02,None,AGTCAGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A03,None,CAACACCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B03,None,GTTGCATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C03,None,AGAGGTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D03,None,GATCTGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E03,None,CAGATGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F03,None,GCATTAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G03,None,CTTGCTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H03,None,TCACAGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A04,None,CAAGCAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B04,None,GATCTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C04,None,GGTACGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D04,None,GATCCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E04,None,GTAGTGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F04,None,GTACTCCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G04,None,TCTGCACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H04,None,TCCTACGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A05,None,TGCATGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B05,None,CAGTCTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C05,None,CCTACCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D05,None,GAGAACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E05,None,GACTGAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F05,None,GTTGAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G05,None,ACACAGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H05,None,CTCATGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A06,None,ACTGGTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B06,None,GTAGCTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C06,None,TGACGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D06,None,CTCTACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E06,None,TGAGCAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F06,None,TCGTTCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G06,None,AGGAAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H06,None,CCTATTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A07,None,TTCCGGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B07,None,GTTCCATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C07,None,ATAACCGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D07,None,AGCTAGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E07,None,TAATCGGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F07,None,ATCCGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G07,None,CTAGGTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H07,None,TCGTCTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A08,None,TGTCCTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B08,None,CTCTTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C08,None,ACGTGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D08,None,TCCAGTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E08,None,TGGATGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F08,None,CAACGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G08,None,CCTTGCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H08,None,GTGTCTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A09,None,CATCGTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B09,None,AGGAGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C09,None,AGCAGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D09,None,CTAGCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E09,None,GTCTAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F09,None,AATAGGCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G09,None,TGTGTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H09,None,GGATCCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A10,None,CATCACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B10,None,AGTGCTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C10,None,CACATGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D10,None,TCCAGATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E10,None,TTCGCCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F10,None,TTGGAAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G10,None,GACAGTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H10,None,ATGGCCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A11,None,AGACCAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B11,None,CACTGAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C11,None,GTGACTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D11,None,CGATGCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E11,None,TGTGAGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F11,None,GTTCACGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G11,None,CGCGAATT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H11,None,AATTCGGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01A12,None,ACAGACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01B12,None,TGCTCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01C12,None,GGAATTCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01D12,None,TGGTACGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01E12,None,CTCTCTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01F12,None,ACCAACCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01G12,None,ACCACTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T01H12,None,CCATCGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A01,None,CTACTCCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B01,None,TCGTTGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C01,None,AGTCCAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D01,None,TGAGTCTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E01,None,CTACGTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F01,None,TAGCATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G01,None,TGAGGACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H01,None,ACTGTGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A02,None,TAGCCGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B02,None,GTCTACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C02,None,CGTTCCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D02,None,TGAGTCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E02,None,ACACCTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F02,None,GCAAGGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G02,None,CGCCTATT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H02,None,ACGTGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A03,None,CCTTGCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B03,None,CGAACGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C03,None,TGTCGTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D03,None,CATGTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E03,None,GACAACAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F03,None,GCATGGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G03,None,TAGGCGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H03,None,CTGTCTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A04,None,GAGTGACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B04,None,CGCGTTAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C04,None,ACTGAGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D04,None,GGTATTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E04,None,TTCGAAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F04,None,GCATGCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G04,None,CTCACAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H04,None,GTTCAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A05,None,GCATAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B05,None,CTCTGAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C05,None,CAGTGACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D05,None,CCGCATAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E05,None,CTAGCTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F05,None,TGCATGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G05,None,TATAGCCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H05,None,TCACCTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A06,None,GCATATGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B06,None,GTCATGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C06,None,AGTCTCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D06,None,GGATGGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E06,None,TGGAGATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F06,None,CGTAGGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G06,None,CGTTGGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H06,None,CACTCAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A07,None,CTAGGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B07,None,TCCAGAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C07,None,CGATATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D07,None,GTAGTCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E07,None,CCTAGGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F07,None,GAACTCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G07,None,ATGGATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H07,None,TATTCCGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A08,None,CATCTCCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B08,None,GAGTTGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C08,None,TTGGAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D08,None,GAAGAGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E08,None,ACCTGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F08,None,TCTCACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G08,None,CAACAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H08,None,TGACTGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A09,None,GTACTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B09,None,GTCTTCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C09,None,GTCATCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D09,None,CCTTATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E09,None,AGGAACGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F09,None,CGTAATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G09,None,GAACCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H09,None,TTATCGCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A10,None,GATGTCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B10,None,AACGTTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C10,None,TTCCTTCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D10,None,AGACGTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E10,None,AGACACAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F10,None,GTCTGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G10,None,CAGTACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H10,None,ATGCTACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A11,None,ACTCAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B11,None,CAGTCAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C11,None,ACTGCTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D11,None,ACTCTCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E11,None,GTAGGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F11,None,CATGCTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G11,None,AGCTCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H11,None,AAGGCGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02A12,None,GGATGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02B12,None,GATCGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02C12,None,TATAGGCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02D12,None,TAATGCGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02E12,None,CTTGCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02F12,None,CTGAACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02G12,None,GCATGGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T02H12,None,ACCAAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A01,None,AAGGCGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B01,None,GACTACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C01,None,CGAACCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D01,None,GCTTAACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E01,None,ACGTTGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F01,None,CGTATTGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G01,None,TTCGTAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H01,None,CCTACGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A02,None,TAGGTACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B02,None,TGGTGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C02,None,ATGGTACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D02,None,GGCCAATT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E02,None,GAACCAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F02,None,CAACCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G02,None,TAGCTTGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H02,None,CACTGACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A03,None,GTTGGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B03,None,ACACCTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C03,None,CATCAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D03,None,GGTATACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E03,None,AGGACTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F03,None,ACTCGAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G03,None,CCGGTATA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H03,None,GGCGAATA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A04,None,CATGCTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B04,None,TGGTCTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C04,None,TCCAACGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D04,None,CTTGAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E04,None,TCTGACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F04,None,TGGAGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G04,None,TGTCTGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H04,None,CAAGTGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A05,None,GAGAGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B05,None,TACCATCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C05,None,CACATCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D05,None,CTCTGTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E05,None,AGCTCTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F05,None,ACACACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G05,None,CGAATTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H05,None,ACTGTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A06,None,AACGTAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B06,None,CAACTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C06,None,CTGACAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D06,None,ATGGATCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E06,None,CATCGATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F06,None,GATCGTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G06,None,GCTTGGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H06,None,GATGGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A07,None,GTCAACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B07,None,CTAGGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C07,None,GAGAAGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D07,None,GTTGTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E07,None,TGACACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F07,None,GGCGTATT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G07,None,CTGATGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H07,None,AACCATGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A08,None,CGATTAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B08,None,AACGAAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C08,None,ACTGCAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D08,None,GACAGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E08,None,TTGCTACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F08,None,ACGTCATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G08,None,GGTTCCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H08,None,CATGCATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A09,None,CGGCATTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B09,None,TGTCGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C09,None,ACTCACAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D09,None,GCCGATAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E09,None,TGCAGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F09,None,AGACACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G09,None,TTCGAACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H09,None,GATGAGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A10,None,CAGACTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B10,None,ACCTCTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C10,None,TCGAACGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D10,None,CTGTAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E10,None,CATGCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F10,None,ATCCTTGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G10,None,TCCTGTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H10,None,AATTGCCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A11,None,GAGACACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B11,None,TGCATCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C11,None,CTCATCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D11,None,GATGTGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E11,None,GATCAGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F11,None,GAAGACGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G11,None,CTTCGTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H11,None,TCACCAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03A12,None,TCTCAGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03B12,None,TTAACGCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03C12,None,GTACTCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03D12,None,AGAGACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03E12,None,CGTATTCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03F12,None,CTACTCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03G12,None,ATCCTACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T03H12,None,ACGTCTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A01,None,TACCGGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B01,None,GTGATCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C01,None,ACAGGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D01,None,GGCCTAAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E01,None,GATCCATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F01,None,ATGGCCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G01,None,ATGGCGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H01,None,ATCCATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A02,None,CTGTGTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B02,None,TACGATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C02,None,ATTACGCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D02,None,TGTGGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E02,None,CGATGCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F02,None,AGAGCTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G02,None,CCTTAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H02,None,ACACAGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A03,None,ATGGAACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B03,None,CATCCAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C03,None,ACGAACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D03,None,CCGCTTAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E03,None,GGATGCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F03,None,TCCTCATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G03,None,TCTGGTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H03,None,AAGGTAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A04,None,TCAGCAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B04,None,CAGAAGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C04,None,GACACTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D04,None,CTAGTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E04,None,ATGGTTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F04,None,CAAGCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G04,None,TTGCCGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H04,None,AAGCTTGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A05,None,ACTCCTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B05,None,ATCGCGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C05,None,TCCACAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D05,None,GATGCATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E05,None,GTCACTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F05,None,TCTCTCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G05,None,TCAGGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H05,None,GCTTCGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A06,None,TGGACTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B06,None,GGATTAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C06,None,GTCTCTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D06,None,TCGATCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E06,None,TTGGCGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F06,None,GTCAGAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G06,None,CTCACTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H06,None,ATCCGCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A07,None,CTTCGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B07,None,GTGTACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C07,None,CACACACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D07,None,TTGCGGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E07,None,CAAGAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F07,None,GAAGGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G07,None,TCGAAGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H07,None,CAACCTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A08,None,TCGACATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B08,None,TCCACTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C08,None,TTGGTACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D08,None,CTAGTGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E08,None,TTGCATCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F08,None,ATCCGGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G08,None,CACTTGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H08,None,GCTAGGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A09,None,CCTTCCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B09,None,ACCAGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C09,None,TCTCGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D09,None,ACAGCTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E09,None,ACCTCATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F09,None,CACAAGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G09,None,TGAGAGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H09,None,GACTTGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A10,None,CAAGACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B10,None,TGTCTCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C10,None,AACGGCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D10,None,GCAATTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E10,None,TGGTTCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F10,None,CGTATACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G10,None,CAGATGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H10,None,GTAGCAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A11,None,TACCTTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B11,None,GCGCAATT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C11,None,TTCGCGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D11,None,AGGTGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E11,None,CACTAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F11,None,TTGCTTGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G11,None,GTGTAGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H11,None,CATCCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04A12,None,AGCAAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04B12,None,GCCGTATA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04C12,None,CAAGTGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04D12,None,ATGCATGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04E12,None,CGAACGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04F12,None,CTCTAGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04G12,None,GTCAGACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T04H12,None,TTATGCGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A01,None,CCATGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B01,None,CTTCTCCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C01,None,TGTGCTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D01,None,CGGCATAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E01,None,AACCATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F01,None,TCCTCTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G01,None,TGACGACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H01,None,ATGCGCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A02,None,CTTGTCCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B02,None,TAGCAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C02,None,AGGAGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D02,None,GTAGGAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E02,None,ACTGCTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F02,None,ACGATGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G02,None,TAGCTAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H02,None,CTACGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A03,None,CCATCGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B03,None,CAGTTCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C03,None,CGATTACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D03,None,GACTGACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E03,None,ACTCGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F03,None,GGAAGCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G03,None,GCAATAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H03,None,CTTCGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A04,None,GAAGGTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B04,None,CTACACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C04,None,GATCGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D04,None,AACGATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E04,None,GAACTGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F04,None,CAACCATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G04,None,AGAGGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H04,None,TGACCTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A05,None,CAGTTGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B05,None,TCACTGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C05,None,ACCATCCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D05,None,TGTCAGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E05,None,GAGAGAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F05,None,TCCTTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G05,None,CCTAATCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H05,None,GGTATAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A06,None,TCGAGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B06,None,GAGACTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C06,None,TCAGACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D06,None,AAGGTACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E06,None,CGGCTAAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F06,None,ATTAGGCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G06,None,ACTCTGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H06,None,TTGGCGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A07,None,GAAGTCCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B07,None,AGACTGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C07,None,TCTGAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D07,None,GTTCGTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E07,None,CAGAGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F07,None,AACGTTGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G07,None,GTCTGACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H07,None,GTGAACAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A08,None,CAGAGACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B08,None,CTACTGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C08,None,GCAACGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D08,None,ATATCGCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E08,None,GCTATTCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F08,None,CGATAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G08,None,AACGGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H08,None,GACAAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A09,None,TGCTCATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B09,None,TGTGTCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C09,None,ACAGTGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D09,None,GATCACCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E09,None,GTCAGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F09,None,AAGCTACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G09,None,GATCTCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H09,None,CACTCTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A10,None,GACAACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B10,None,GTACGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C10,None,TGGAAGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D10,None,CATCTGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E10,None,AACGCGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F10,None,CATCGTAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G10,None,GTGTGACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H10,None,AACGTACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A11,None,GACACTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B11,None,CAACGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C11,None,CTGACACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D11,None,ACTCTCTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E11,None,TGACTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F11,None,AGGTCTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G11,None,ATGCAAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H11,None,TTAACGGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05A12,None,AGGTCTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05B12,None,CACAGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05C12,None,AGGTAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05D12,None,TCGAGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05E12,None,GATGCTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05F12,None,ACAGAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05G12,None,CTACGAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T05H12,None,CTCTTGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A01,None,CTGTGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B01,None,AACGAACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C01,None,AGCTACCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D01,None,CCATAACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E01,None,GGTACGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F01,None,TACCATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G01,None,TTCGTTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H01,None,ACAGGAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A02,None,TGGATCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B02,None,TTCGCCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C02,None,CGATCCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D02,None,TCACCACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E02,None,TGACCTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F02,None,GTCATGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G02,None,GAGATGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H02,None,ACCTGAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A03,None,TTGCATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B03,None,TTCCTAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C03,None,CGTTATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D03,None,TGCTTCCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E03,None,TTAAGGCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F03,None,AGCAACGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G03,None,CACTTCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H03,None,GACAAGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A04,None,CAGAACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B04,None,GACAGAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C04,None,TTCCAAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D04,None,TGTGTGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E04,None,GGTTAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F04,None,CGAATTGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G04,None,GCTATTGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H04,None,GTGTTCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A05,None,GTTGGTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B05,None,CCAAGCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C05,None,CCTTATGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D05,None,TCTGGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E05,None,CTTCAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F05,None,TAGGTAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G05,None,CCTATAGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H05,None,CACTACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A06,None,TTGGCCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B06,None,TCAGTGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C06,None,TGTGCAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D06,None,CATCGAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E06,None,GTGTACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F06,None,TGGTCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G06,None,TGAGACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H06,None,CGTAGCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A07,None,ACAGCACT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B07,None,CGCGATTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C07,None,GGAAGGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D07,None,GGCGTTAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E07,None,TCTGGAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F07,None,CTAGAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G07,None,AGACTCAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H07,None,AGAGCACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A08,None,CCATATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B08,None,GGCCTATA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C08,None,GAACTCCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D08,None,GTTCTCCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E08,None,CAAGAGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F08,None,AAGCGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G08,None,GGTTGGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H08,None,AGTCACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A09,None,GCAATACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B09,None,ACACTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C09,None,CTCATCTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D09,None,CCGCAATA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E09,None,GTACCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F09,None,TCGTACGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G09,None,CAGTACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H09,None,TACCGGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A10,None,CTCTTCAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B10,None,AAGCAAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C10,None,TGCAGTAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D10,None,TGCAACGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E10,None,GCGGATAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F10,None,TAATGCCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G10,None,CGTTGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H10,None,CCTAGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A11,None,GACTCACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B11,None,TACGCGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C11,None,TGTCACAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D11,None,GTGTGTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E11,None,AGCACAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F11,None,CTGAACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G11,None,AGAGTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H11,None,TCCATCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06A12,None,TTGGTTGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06B12,None,GCTTGCAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06C12,None,TGCTACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06D12,None,GCATCGTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06E12,None,GTGAACTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06F12,None,AGTCGAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06G12,None,CCTTCGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T06H12,None,CTCACTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A01,None,AGTGGACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B01,None,GAGTGTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C01,None,AACCAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D01,None,CACACAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E01,None,TCGATGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F01,None,CCGCTATT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G01,None,TCTGTCTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H01,None,TGTCGACA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A02,None,GTGATGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B02,None,GTAGACGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C02,None,AGCATCGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D02,None,CGCCATAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E02,None,AGGAGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F02,None,GGTAGGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G02,None,TACCTACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H02,None,TGCTAGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A03,None,TTGCCGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B03,None,TCTGACAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C03,None,CTACCAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D03,None,ATGCGGAA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E03,None,CAGTTCTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F03,None,GTCTTGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G03,None,AGTCACTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H03,None,GCTTATGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A04,None,GAACGATG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B04,None,ACACTGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C04,None,GACTGTGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D04,None,AACCGCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E04,None,CTGAGTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F04,None,AGCTTGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G04,None,CAACTCCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H04,None,CAGAGTGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A05,None,GATGTGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B05,None,AGCTGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C05,None,GCGCATTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D05,None,GCAAGCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E05,None,AGTGAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F05,None,TGTCAGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G05,None,GTCTTGTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H05,None,TTCCAACC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A06,None,AACGCCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B06,None,ACGTAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C06,None,GTGATGAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D06,None,AAGGCCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E06,None,GAGTTCTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F06,None,GTTGTCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G06,None,TAGGAAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H06,None,TCACTCTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A07,None,GAACACGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B07,None,AGCAGAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C07,None,AGTGCTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D07,None,TGTCGAGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E07,None,TCCTAGCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F07,None,TATTGGCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G07,None,CGTTCGTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H07,None,GAAGTCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A08,None,GTGACAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B08,None,ACCTACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C08,None,AGGATCGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D08,None,TCTGAGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E08,None,CCAAGCAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F08,None,TTCCATCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G08,None,GTCTCAGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H08,None,ACGTAGGA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A09,None,TGGTGTTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B09,None,CCATATCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C09,None,AGGATGCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D09,None,GTAGAGGT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E09,None,CTCTACAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F09,None,GAAGCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G09,None,GGAACCTT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H09,None,GAAGCTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A10,None,GAACACCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B10,None,GTGACTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C10,None,TAGCCGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D10,None,ATCGTAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E10,None,GTTGCAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F10,None,TCACCTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G10,None,TTCGATCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H10,None,GATGGTTC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A11,None,CGTAATGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B11,None,TTGCTTCG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C11,None,CTAGGATC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D11,None,ACCACAAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E11,None,GGTACCTA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F11,None,AGTCCTCT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G11,None,ATTACCGG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H11,None,GACTTGTG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16A12,None,TCTCTGAC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16B12,None,ATCGTACG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16C12,None,ATCCATCC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16D12,None,TGGTACCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16E12,None,GCATCGAT,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16F12,None,CGTTAAGC,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16G12,None,GTCTCTCA,Travis Ruff,N,RI,Nicole,L<lane>_<request>
<fcid>,<lane>,L<lane>T16H12,None,ACCAGAAG,Travis Ruff,N,RI,Nicole,L<lane>_<request>
"""
